name: email-daily

on:
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Daily Run
    steps:
    - uses: actions/checkout@v2
      name: checkout repo content
    - uses: actions/setup-python@v2
      name: setup python
      with:
        python-version: '3.7.7'
    - run: |
        python main.py
      name: execute py script